import type { DetailOutput } from "./generate-detail-page";

const origin = "https://living-books-beta.vercel.app";
const description = "답장에 흔들리고 같은 싸움을 반복할 때 펼치는 연애의 기술2. 5부·20개 실전 수업, 대화문 20개, 작성 양식과 일주일 실행표를 담은 HTML 전자책입니다.";

export function loveSkills2Details(): DetailOutput {
  const detailHtml = `<style>
.ls2-detail{--ink:#253f3b;--rose:#a54556;max-width:860px;margin:0 auto;background:#fffcf7;color:var(--ink);font-family:Arial,'Malgun Gothic',sans-serif;line-height:1.8;overflow-wrap:anywhere}
.ls2-detail *{box-sizing:border-box}.ls2-detail section{padding:44px 32px;border-bottom:1px solid #e7ddd3}.ls2-detail h1{font-size:clamp(36px,7vw,64px);line-height:1.2;letter-spacing:-.045em;margin:16px 0}.ls2-detail h2{font-size:clamp(25px,4vw,34px);line-height:1.4;letter-spacing:-.03em;margin:10px 0 22px}.ls2-detail h3{font-size:20px;margin:0 0 8px}.ls2-detail p{margin:12px 0}.ls2-detail .eyebrow{color:var(--rose);font-size:13px;font-weight:800;letter-spacing:.07em}.ls2-detail .hero{background:#f4eee5;text-align:center}.ls2-detail .lead{font-size:20px}.ls2-detail .pills{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:26px}.ls2-detail .pills span{padding:8px 15px;border:1px solid #d6c6bd;border-radius:30px;font-size:14px}.ls2-detail .grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.ls2-detail .box{background:white;padding:23px;border:1px solid #e7ddd3;border-radius:15px}.ls2-detail blockquote{margin:20px 0;padding:24px;background:#eaf0eb;border-left:4px solid #527a6c;border-radius:0 12px 12px 0}.ls2-detail .muted{font-size:14px;color:#62706a}.ls2-detail ol,.ls2-detail ul{padding-left:24px}.ls2-detail li{margin-bottom:12px}.ls2-detail .cta{display:inline-block;padding:15px 25px;border-radius:10px;background:var(--ink);color:#fff;text-decoration:none;font-weight:700}.ls2-detail .end{text-align:center;background:#eaf0eb}.ls2-detail details{padding:17px 0;border-bottom:1px solid #dedbd3}.ls2-detail summary{cursor:pointer;font-weight:700}.ls2-detail a:focus-visible,.ls2-detail summary:focus-visible{outline:3px solid #a54556;outline-offset:4px}@media(max-width:540px){.ls2-detail section{padding:32px 20px}.ls2-detail .grid{grid-template-columns:1fr}.ls2-detail .lead{font-size:18px}}
</style><article class="ls2-detail">
<section class="hero"><span class="eyebrow">보내기 버튼을 누르기 전에</span><h1>연애의 기술2</h1><p class="lead">답장 하나에 흔들리는 밤,<br>추측 대신 꺼낼 말을 준비하세요.</p><p>연락에 흔들리고, 서운함을 삼키는 당신을 위한 대화 실전서</p><div class="pills"><span>5부 · 20개 실전 수업</span><span>대화문 20개</span><span>빈 양식 + 작성 예시</span></div></section>
<section><span class="eyebrow">01 · 이런 순간에 펼칩니다</span><h2>할 말은 많은데,<br>보내고 나면 후회하나요?</h2><div class="grid"><div class="box"><h3>“답이 없으니 마음이 식었겠지.”</h3><p>확인한 사실과 내가 붙인 뜻이 뒤섞일 때.</p></div><div class="box"><h3>“서운하다고만 했는데 또 싸워요.”</h3><p>말문을 열어도 요청은 전하지 못할 때.</p></div><div class="box"><h3>“미안하다는 말은 늘 들어요.”</h3><p>사과 뒤에 달라진 행동이 보이지 않을 때.</p></div><div class="box"><h3>“어디까지 양보해야 하죠?”</h3><p>사랑과 내 경계 사이에서 망설일 때.</p></div></div></section>
<section><span class="eyebrow">02 · 책을 읽고 남길 것</span><h2>감정에서 요청으로.<br>약속에서 실제 행동으로.</h2><ol><li><b>사실과 해석을 나눕니다.</b> 상대의 마음을 단정하기 전에 모르는 칸을 남깁니다.</li><li><b>실행 가능한 말을 만듭니다.</b> 연락 약속, 서운함 전달, 대화 재개를 내 상황에 맞게 씁니다.</li><li><b>다음 선택을 기록합니다.</b> 말보다 실행을 보고 유지·재협의·거리두기를 생각합니다.</li></ol><p class="muted">대화문과 기록지는 이 책의 연습 도구입니다. 상대의 협력이나 관계 회복을 보장하지 않습니다.</p></section>
<section><span class="eyebrow">03 · 본문 미리보기</span><h2>“왜 늘 나만 기다려?”를<br>이렇게 바꿔봅니다.</h2><p><b>확인한 사실:</b> 만나기로 한 시간이 출발한 뒤 바뀌었다.</p><p><b>아직 모르는 점:</b> 상대는 언제 변경 가능성을 알았을까?</p><blockquote>“오늘 약속이 출발한 뒤 바뀌어서 서운했어. 나는 일정을 미리 정하고 싶어. 다음에는 바뀔 가능성을 알게 되면 먼저 알려줄 수 있어?”</blockquote><p>상대가 거절하거나 같은 일이 반복될 때 어떻게 확인하고 판단할지도 함께 다룹니다.</p><p class="muted">가상 상황으로 만든 본문 연습 예시입니다.</p></section>
<section><span class="eyebrow">04 · 구성</span><h2>읽을 내용과 쓸 도구가<br>함께 있습니다.</h2><ol><li><b>1부. 답장 하나에 관계 전체를 걸지 않기</b><br>사실·추측, 메시지 대기, 반복 고리, 내 기준.</li><li><b>2부. 서운함을 싸움 대신 요청으로 전하기</b><br>연락 합의, 구체적 요청, 듣기, 관계 확인.</li><li><b>3부. 같은 싸움에서 다른 결말 만들기</b><br>중단·재개, 책임 있는 사과, 약속 실행 기록.</li><li><b>4부. 사랑해도 양보하지 않을 기준 세우기</b><br>디지털 경계, 동의, 관계 판단, 안전과 도움.</li><li><b>5부. 읽고 끝내지 않는 작은 연습</b><br>고마움, 변화 점검, 일주일 연습, 재시작 카드.</li></ol><div class="box"><h3>부록 3종</h3><p>A. 보내기 전 점검표 + 빈 양식 6종<br>B. 내 말로 고쳐 쓰는 대화문 20개<br>C. 일주일 실행표 + 상황별 다시 찾기</p></div></section>
<section><span class="eyebrow">05 · 나에게 맞는 책인가요?</span><h2>눈치 대신 질문을,<br>참기 대신 기준을 찾는 분께.</h2><p>연락과 갈등에서 반복되는 장면을 바꾸고 싶은 성인 독자를 위한 책입니다. 기존 《연애의 기술》을 읽지 않아도 시작할 수 있습니다.</p><p>가상의 인물과 대화로 연습하며, 참고 자료와 적용 범위를 책 끝에 안내합니다. 상대를 진단하거나 조종하는 방법, 재회·관계 회복 보장은 제공하지 않습니다.</p><p class="muted">위협이나 강요가 있다면 대화 연습보다 안전과 지원을 먼저 선택하세요.</p></section>
<section><span class="eyebrow">06 · 이용 안내</span><h2>궁금한 점부터 확인하세요.</h2><details><summary>기존 책과 무엇이 다른가요?</summary><p>기존 책은 보존하고, 이번 책은 연락·서운함·반복 갈등을 실제 행동으로 다루는 20개 수업으로 새로 썼습니다. 독립해서 읽을 수 있습니다.</p></details><details><summary>PDF를 내려받는 책인가요?</summary><p>기존 방식의 HTML 전자책입니다. 웹에서 읽고, 아임웹에는 코드·iframe 방식으로 연결합니다.</p></details><details><summary>상대가 같이 읽어야 하나요?</summary><p>메모와 요청 초안은 혼자 쓸 수 있습니다. 두 사람의 약속은 상대의 동의를 받아야 합의가 됩니다.</p></details><details><summary>양식에 입력하면 자동 저장되나요?</summary><p>아닙니다. 빈 양식과 예시를 개인 메모장에 복사해 사용하는 구성입니다.</p></details><details><summary>일주일이면 관계가 달라지나요?</summary><p>일주일은 선택 가능한 연습 일정입니다. 관계 변화의 기간이나 결과를 보장하지 않습니다.</p></details></section>
<section class="end"><span class="eyebrow">07 · 오늘의 첫 행동</span><h2>보내려던 그 문장,<br>사실과 추측부터 나눠보세요.</h2><p>지금 필요한 절부터 골라 읽으세요.</p><a class="cta" href="${origin}/premium/love-skills-2/read">목차와 본문 열기 →</a><p class="muted">가격·구매·환불 조건은 판매처의 실제 안내를 확인하세요.</p></section>
</article>`;
  return {
    id: "love-skills-2", title: "연애의 기술2", emoji: "💕", detailHtml, detailSize: detailHtml.length,
    metaDesc: description,
    coverPrompt: `용도: HTML 전자책 소개용 평면 표지, 세로 2:3. 따뜻한 아이보리 바탕과 딥 틸·코럴의 선명한 대비. 서로 마주 보는 독립적인 두 도자기 말풍선과 작은 황동 다리로 대화와 경계를 표현. 넉넉한 여백, 완전한 피사체, 고급 출판 편집 디자인. 그림에는 글자를 생성하지 말고 한국어는 후조판: 큰 제목 '연애의 기술2', 부제 '연락에 흔들리고, 서운함을 삼키는 당신을 위한 대화 실전서'. 웹 전자책임을 표시. 실물 책·미제공 강의·후기·성과 보장·인증·가짜 QR 없음. 3D 목업이 필요할 경우 동일 표지의 별도 소개 이미지로 만들고 종이책 배송을 암시하지 않기.`,
    thumbnailPrompt: `가로 16:9 소개 썸네일. 오른쪽에는 코럴과 딥 틸 도자기 말풍선 두 개가 마주한 입체 장면, 왼쪽에는 짧은 한국어 카피를 위한 여백. 아이보리 배경, 강한 명암, 소형 화면에서도 읽히는 단순한 구도. 이미지에는 텍스트 없이 생성하고 후조판: '답장 하나에 / 흔들리는 밤' 및 작은 제목 '연애의 기술2'. 상처·공포 자극, 조작된 채팅, 허위 후기, 연애 성공률·기간 보장 없이 문제와 실제 대화 도구에 초점.`,
    marketingCopy: `메인: 답장 하나에 흔들리는 밤, 추측 대신 꺼낼 말을 준비하세요.\n서브: 연락·서운함·반복되는 싸움을 다루는 20개 실전 수업.\n제공: 5부·20개 수업 / 대화문 20개 / 점검표와 빈 양식 6종 / 일주일 실행표.\n짧은 소개: '왜 늘 나만 기다려?'를 보내기 전에. 사실과 추측을 나누고, 내 바람을 구체적인 요청으로 바꿔보세요.\nCTA: 목차에서 지금 필요한 상황을 고르세요.\n공개 판매 주소: https://vipup.site/love-skills-2 (아임웹 상품 연결 확인 필요)\n형식: HTML 전자책 · 아임웹 코드/iframe 임베딩. 빈 양식은 복사해서 사용.\n범위: 관계 회복·재회·기간별 효과를 보장하지 않습니다. 가격·할인·환불 조건 미확정.`,
  };
}
